name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install bash loadable dev files and build tools
      run: |
        sudo apt-get update
        sudo apt-get install -y bash-builtins build-essential pkg-config indent

    - name: configure
      run: ./configure

    - name: check
      run: make check

    - name: format
      run: make format
